// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: c2s/c2s.proto

package c2s

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// client  <-> server  10000 - 19999
type MessageCmd int32

const (
	MessageCmd_NULL   MessageCmd = 0
	MessageCmd_Login  MessageCmd = 1
	MessageCmd_FRAME  MessageCmd = 2
	MessageCmd_FRAMES MessageCmd = 3
)

// Enum value maps for MessageCmd.
var (
	MessageCmd_name = map[int32]string{
		0: "NULL",
		1: "Login",
		2: "FRAME",
		3: "FRAMES",
	}
	MessageCmd_value = map[string]int32{
		"NULL":   0,
		"Login":  1,
		"FRAME":  2,
		"FRAMES": 3,
	}
)

func (x MessageCmd) Enum() *MessageCmd {
	p := new(MessageCmd)
	*p = x
	return p
}

func (x MessageCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_c2s_c2s_proto_enumTypes[0].Descriptor()
}

func (MessageCmd) Type() protoreflect.EnumType {
	return &file_c2s_c2s_proto_enumTypes[0]
}

func (x MessageCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageCmd.Descriptor instead.
func (MessageCmd) EnumDescriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_OK ErrorCode = 0
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
	}
	ErrorCode_value = map[string]int32{
		"OK": 0,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_c2s_c2s_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_c2s_c2s_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{1}
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Uid    string  `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Fid    int32   `protobuf:"varint,3,opt,name=fid,proto3" json:"fid,omitempty"`
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LoginResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LoginResp) GetFid() int32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

type Cmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd int32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Opt int32 `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{3}
}

func (x *Cmd) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Cmd) GetOpt() int32 {
	if x != nil {
		return x.Opt
	}
	return 0
}

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid  int32  `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Uid  string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Cmds []*Cmd `protobuf:"bytes,3,rep,name=cmds,proto3" json:"cmds,omitempty"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{4}
}

func (x *Frame) GetFid() int32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *Frame) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Frame) GetCmds() []*Cmd {
	if x != nil {
		return x.Cmds
	}
	return nil
}

type FrameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame []*Frame `protobuf:"bytes,1,rep,name=frame,proto3" json:"frame,omitempty"`
}

func (x *FrameReq) Reset() {
	*x = FrameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameReq) ProtoMessage() {}

func (x *FrameReq) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameReq.ProtoReflect.Descriptor instead.
func (*FrameReq) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{5}
}

func (x *FrameReq) GetFrame() []*Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type FrameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Uid    string  `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Fid    int32   `protobuf:"varint,3,opt,name=fid,proto3" json:"fid,omitempty"`
}

func (x *FrameResp) Reset() {
	*x = FrameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResp) ProtoMessage() {}

func (x *FrameResp) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResp.ProtoReflect.Descriptor instead.
func (*FrameResp) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{6}
}

func (x *FrameResp) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FrameResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FrameResp) GetFid() int32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

type FramesNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame []*Frame `protobuf:"bytes,1,rep,name=frame,proto3" json:"frame,omitempty"`
}

func (x *FramesNotify) Reset() {
	*x = FramesNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c2s_c2s_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FramesNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FramesNotify) ProtoMessage() {}

func (x *FramesNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c2s_c2s_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FramesNotify.ProtoReflect.Descriptor instead.
func (*FramesNotify) Descriptor() ([]byte, []int) {
	return file_c2s_c2s_proto_rawDescGZIP(), []int{7}
}

func (x *FramesNotify) GetFrame() []*Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

var File_c2s_c2s_proto protoreflect.FileDescriptor

var file_c2s_c2s_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x32, 0x73, 0x2f, 0x63, 0x32, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x63, 0x32, 0x73, 0x22, 0x2e, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x1c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x54, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x23, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x63, 0x32, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6f, 0x70, 0x74, 0x22, 0x49, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x63, 0x32, 0x73, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x22, 0x2c,
	0x0a, 0x08, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x05, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x32, 0x73, 0x2e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x09,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x32, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66,
	0x69, 0x64, 0x22, 0x30, 0x0a, 0x0c, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x20, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x32, 0x73, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x2a, 0x38, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x6d, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x52, 0x41, 0x4d, 0x45,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x53, 0x10, 0x03, 0x2a, 0x13,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x69, 0x72, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x63, 0x73, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x32, 0x73, 0x3b, 0x63, 0x32, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_c2s_c2s_proto_rawDescOnce sync.Once
	file_c2s_c2s_proto_rawDescData = file_c2s_c2s_proto_rawDesc
)

func file_c2s_c2s_proto_rawDescGZIP() []byte {
	file_c2s_c2s_proto_rawDescOnce.Do(func() {
		file_c2s_c2s_proto_rawDescData = protoimpl.X.CompressGZIP(file_c2s_c2s_proto_rawDescData)
	})
	return file_c2s_c2s_proto_rawDescData
}

var file_c2s_c2s_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_c2s_c2s_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_c2s_c2s_proto_goTypes = []interface{}{
	(MessageCmd)(0),      // 0: c2s.MessageCmd
	(ErrorCode)(0),       // 1: c2s.ErrorCode
	(*Result)(nil),       // 2: c2s.Result
	(*LoginReq)(nil),     // 3: c2s.LoginReq
	(*LoginResp)(nil),    // 4: c2s.LoginResp
	(*Cmd)(nil),          // 5: c2s.Cmd
	(*Frame)(nil),        // 6: c2s.Frame
	(*FrameReq)(nil),     // 7: c2s.FrameReq
	(*FrameResp)(nil),    // 8: c2s.FrameResp
	(*FramesNotify)(nil), // 9: c2s.FramesNotify
}
var file_c2s_c2s_proto_depIdxs = []int32{
	2, // 0: c2s.LoginResp.result:type_name -> c2s.Result
	5, // 1: c2s.Frame.cmds:type_name -> c2s.Cmd
	6, // 2: c2s.FrameReq.frame:type_name -> c2s.Frame
	2, // 3: c2s.FrameResp.result:type_name -> c2s.Result
	6, // 4: c2s.FramesNotify.frame:type_name -> c2s.Frame
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_c2s_c2s_proto_init() }
func file_c2s_c2s_proto_init() {
	if File_c2s_c2s_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c2s_c2s_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c2s_c2s_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FramesNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c2s_c2s_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2s_c2s_proto_goTypes,
		DependencyIndexes: file_c2s_c2s_proto_depIdxs,
		EnumInfos:         file_c2s_c2s_proto_enumTypes,
		MessageInfos:      file_c2s_c2s_proto_msgTypes,
	}.Build()
	File_c2s_c2s_proto = out.File
	file_c2s_c2s_proto_rawDesc = nil
	file_c2s_c2s_proto_goTypes = nil
	file_c2s_c2s_proto_depIdxs = nil
}
